name: Publish Docker images
on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image Pocketbase
        uses: docker/build-push-action@v6
        with:
          context: ./apps/pocketbase
          file: ./apps/pocketbase/Dockerfile
          push: true
          build-args: PB_VERSION=0.22.21
          tags: ghcr.io/fredealexandre/smartflow-pocketbase:prod

      - name: Build and push Docker image Next.js
        uses: docker/build-push-action@v6
        with:
          context: ./apps/website
          file: ./apps/website/Dockerfile
          target: nextjs
          push: true
          tags: ghcr.io/fredealexandre/smartflow-website:prod
