name: Publish Docker images
on:
 push:
   branches:
     - main

permissions:
  packages: write

jobs:
  push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image Pocketbase
        uses: docker/build-push-action@v6
        with:
          context: ./docker-images/pocketbase
          file: ./docker-images/pocketbase/Dockerfile
          push: true
          build-args:
            PB_VERSION: 0.22.20
          tags: ghcr.io/fredealexandre/smartflow-pocketbase:prod

      - name: Build and push Docker image Next.js
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker-images/monorepo-apps/Dockerfile
          target: nextjs
          push: true
          tags: ghcr.io/fredealexandre/smartflow-netxjs:prod
