name: Publish Docker images
on:
 push:
   branches:
     - 'main'

permissions:
  packages: write

jobs:
  push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: [docker-images/pocketbase/Dockerfile, docker-images/monorepo-apps/Dockerfile]
        tag: [pocketbase, netxjs]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "COMMIT_SHORT_SHA=$calculatedSha" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{ matrix.dockerfile }}  # Dynamically select Dockerfile
          push: true
          tags: ghcr.io/fredealexandre/smartflow:${{ matrix.tag }}:prod
